### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte

### ISSUE THREAD

**Issue by sparrowhe** [kooky126/easydl2labelImg#1]
```
Traceback (most recent call last):
  File "main.py", line 11, in <module>
    easydl2labelImg.downloaddateset(args.dataset_id,args.xmlpath)
  File "L:\works\easydl2labelImg-master\easydl2labelImg.py", line 188, in downloaddateset
    annotated,size = downloaddatesetpage(dataset_id,path,annotated,offset)
  File "L:\works\easydl2labelImg-master\easydl2labelImg.py", line 160, in downloaddatesetpage
    data = getdateset(dataset_id,annotated,offset)
  File "L:\works\easydl2labelImg-master\easydl2labelImg.py", line 150, in getdateset
    data = json.loads(content.decode('utf-8'))
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
```

**Comment by kooky126** [comment]
官方链接参数调整，json数据gzip压缩了，已调整代码
