### ISSUE TITLE
下载错误

### ISSUE THREAD

**Issue by Tianshuo-Xu** [kooky126/easydl2labelImg#3]
Traceback (most recent call last):
  File "/Users/tianshuoxu/easydl2labelImg/test.py", line 3, in <module>
    easydl2labelImg.downloaddateset(64052, "bc")
  File "/Users/tianshuoxu/easydl2labelImg/easydl2labelImg.py", line 186, in downloaddateset
    annotated,size = downloaddatesetpage(dataset_id,path,annotated,offset)
正在下载图片：bc/work/dragonboat-web/uploadDir/988807782_376586-2-u-1582281681205-1w8r6zc.ni1n.png
  File "/Users/tianshuoxu/easydl2labelImg/easydl2labelImg.py", line 170, in downloaddatesetpage
    downloadimage(url,path,name)
  File "/Users/tianshuoxu/easydl2labelImg/easydl2labelImg.py", line 127, in downloadimage
    content = getwithcookie(url,None,"image")
  File "/Users/tianshuoxu/easydl2labelImg/easydl2labelImg.py", line 94, in getwithcookie
    request = urllib.request.Request(url=request_url, data=params)
  File "/Users/tianshuoxu/miniconda3/lib/python3.7/urllib/request.py", line 328, in __init__
    self.full_url = url
  File "/Users/tianshuoxu/miniconda3/lib/python3.7/urllib/request.py", line 354, in full_url
    self._parse()
  File "/Users/tianshuoxu/miniconda3/lib/python3.7/urllib/request.py", line 383, in _parse
    raise ValueError("unknown url type: %r" % self.full_url)
ValueError: unknown url type: '//ai.baidu.com/easydl/entity/raw?datasetId=64052&id=780fb274497245e4baf95b0576a5b273481ec202ed30b5ad7a32f27997790341&type=2'
请问您知道是为什么吗？

**Comment by cydawn** [comment]
将easydl2labelImg.py文件的第175行  url = object['url']   改为  url = "https:" + object['url']

**Comment by Tianshuo-Xu** [comment]
好的！谢谢
